"""
Podcast Bot CLI Worker

This is the main orchestrator for the Podcast Bot pipeline. 
It accepts a JSON plan (generated by an LLM orchestrator) containing episode topics,
performs deep research on those topics using the Gemini API, and attempts to upload 
the compiled research to NotebookLM to generate an audio podcast.

Usage:
    export GEMINI_API_KEY="your-api-key"
    python podcast_cli.py --plan test_plan.json
"""
import argparse
import asyncio
import json
import logging
import os
import re
import aiohttp

# Set up logging for console output
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class LinearWorker:
    """
    A sequential worker that handles one episode at a time.
    It manages the transition from a research prompt to a saved markdown file,
    and then invokes the NotebookLM automator.
    """
    def __init__(self, research_dir="research_output"):
        self.research_dir = research_dir
        
        # We rely on the GEMINI_API_KEY environment variable to hit the Gemini API.
        self.gemini_api_key = os.environ.get("GEMINI_API_KEY")
        if not self.gemini_api_key:
            logging.warning("GEMINI_API_KEY is not set. Deep research may fail.")
            
        os.makedirs(self.research_dir, exist_ok=True)
        
    def sanitize_filename(self, title: str) -> str:
        """Converts an episode title into a safe file path string."""
        clean = re.sub(r'[^a-zA-Z0-9_\-]', '_', title)[:50]
        return f"{clean}.md"

    async def run_deep_research(self, prompt: str, title: str) -> str:
        """
        Calls the Gemini REST API directly using `aiohttp` to perform deep research.
        
        We use the `gemini-3.1-pro-preview` model for advanced generation.
        The result is saved to disk as a Markdown file which acts as the 'Source Material'
        for NotebookLM.
        """
        logging.info("Starting Gemini Deep Research...")
        
        async with aiohttp.ClientSession() as session:
            url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-pro-preview:generateContent?key={self.gemini_api_key}"
            headers = {"Content-Type": "application/json"}
            payload = {
                "contents": [{"parts": [{"text": f"Deep research on: {prompt}"}]}]
            }
            
            async with session.post(url, headers=headers, json=payload) as resp:
                if resp.status != 200:
                    text = await resp.text()
                    raise Exception(f"API Error {resp.status}: {text}")
                data = await resp.json()
                
                # Extract the pure markdown text from the Gemini response structure
                research_content = data['candidates'][0]['content']['parts'][0]['text']

        # Save research permanently to the file system
        filename = self.sanitize_filename(title)
        filepath = os.path.join(self.research_dir, filename)
        
        with open(filepath, 'w') as f:
            f.write(f"# Research: {title}\n\n{research_content}")
            
        logging.info(f"Research saved to {filepath}")
        return filepath

    async def run_notebooklm(self, project_name: str, research_path: str, podcast_prompt: str) -> str:
        """
        Invokes the NotebookLM UI Automator script to upload the generated research.
        """
        logging.info(f"Uploading research to NotebookLM project: {project_name}")
        import sys
        
        # Ensure Python can resolve the local virtual environment packages if run externally
        sys.path.append('/Volumes/hermes/projects/podcast-bot/venv/lib/python3.11/site-packages')
        
        # We import the automator script here to avoid failing fast if `nodriver` is missing,
        # allowing the research phase to succeed even if automation fails.
        from notebooklm_automator import upload_research
        
        await upload_research(project_name, research_path)
        return research_path

async def main():
    parser = argparse.ArgumentParser(description="Execute a Podcast Plan JSON")
    parser.add_argument("--plan", required=True, help="Path to the downloaded plan.json")
    args = parser.parse_args()

    try:
        with open(args.plan, 'r') as f:
            data = json.load(f)
            topic = data['topic']
            episodes = data['episodes']
    except Exception as e:
        logging.error(f"Failed to load plan file: {e}")
        return

    worker = LinearWorker()
    logging.info(f"Starting Podcast Generation for: {topic}")

    for idx, ep in enumerate(episodes):
        ep_num = idx + 1
        title = ep['title']
        
        logging.info(f"[Ep {ep_num}/{len(episodes)}] Starting: {title}")
        
        try:
            # Step 1: Perform research
            research_path = await worker.run_deep_research(ep['researchPrompt'], title)
            logging.info(f"Research saved to: {research_path}")
            
            # Step 2: Upload to NotebookLM
            audio_path = await worker.run_notebooklm(
                project_name=f"{topic} - {title}",
                research_path=research_path,
                podcast_prompt=ep.get('podcastPrompt', '')
            )
            
            logging.info(f"Successfully processed episode {ep_num}: {title}. Output: {audio_path}")
            
        except Exception as e:
            logging.error(f"Error executing episode {ep_num}: {e}")

if __name__ == "__main__":
    asyncio.run(main())
